from typing import List, Dict, Any
from jinja2 import Template
from ..models import Finding

HTML_TMPL = """
<html>
<head>
  <meta charset="utf-8">
  <title>RepoSafe 报告</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    :root{--bg:#f6f8fa;--card:#ffffff;--accent:#2b6cb0;--muted:#6b7280}
    body{font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial; background:var(--bg); margin:0; padding:24px}
    .container{max-width:1100px;margin:0 auto}
    header{display:flex;align-items:center;gap:16px}
    h1{margin:0;font-size:20px}
    .meta{color:var(--muted);font-size:13px}
    .cards{display:flex;gap:12px;margin-top:16px;margin-bottom:20px}
    .card{background:var(--card);padding:12px;border-radius:8px;box-shadow:0 1px 2px rgba(16,24,40,0.05);flex:1}
    .big{font-size:20px;font-weight:600}
    table{width:100%;border-collapse:collapse;background:var(--card);border-radius:8px;overflow:hidden}
    th,td{padding:12px;border-bottom:1px solid #eef2f7;text-align:left}
    thead th{background:#f8fafc;font-weight:600}
    .badge{display:inline-block;padding:4px 8px;border-radius:999px;color:#fff;font-weight:700;font-size:12px}
    .badge.high{background:#e53e3e}
    .badge.medium{background:#dd6b20}
    .badge.low{background:#3182ce}
    .badge.info{background:#6b46c1}
    details{margin-top:6px}
    .file{color:#0f172a;font-weight:600}
    .muted{color:var(--muted)}
    footer{margin-top:18px;color:var(--muted);font-size:13px}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>RepoSafe 安全扫描报告</h1>
    </header>
    <div class="meta">扫描路径: {{scanned_path}} • 扫描时间: {{scan_time}}</div>

    <div class="cards">
      <div class="card">
        <div class="muted">总风险</div>
        <div class="big">{{summary.total}}</div>
      </div>
      <div class="card">
        <div class="muted">高危</div>
        <div class="big">{{summary.high}}</div>
      </div>
      <div class="card">
        <div class="muted">中危</div>
        <div class="big">{{summary.medium}}</div>
      </div>
      <div class="card">
        <div class="muted">低危</div>
        <div class="big">{{summary.low}}</div>
      </div>
      <div class="card">
        <div class="muted">信息</div>
        <div class="big">{{summary.info}}</div>
      </div>
    </div>

    <table>
      <thead>
        <tr><th style="width:120px">严重等级</th><th style="width:140px">扫描器</th><th>详情 / 规则 / 修复建议</th><th style="width:220px">文件</th><th style="width:80px">行号</th></tr>
      </thead>
      <tbody>
      {% for f in findings %}
        <tr>
          <td>
            <span class="badge {{f.severity_class}}">{{f.severity_cn}}</span>
          </td>
          <td>{{f.scanner}}</td>
          <td>
            <div>{{f.message}}</div>
            <details>
              <summary class="muted">规则: {{f.rule_id or 'N/A'}} • 点击查看修复建议</summary>
              <div style="margin-top:8px">{{f.recommendation or '无'}}</div>
            </details>
          </td>
          <td><div class="file">{{f.file or ''}}</div></td>
          <td>{{f.line or ''}}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    <footer>
      Report generated by RepoSafe • {{scan_time}} • Scanned path: {{scanned_path}}
    </footer>
  </div>
</body>
</html>
"""


class HTMLReporter:
  def __init__(self, out: str = 'report.html'):
    self.out = out

  def _map_severity(self, sev):
    # Accept either Severity enum or string
    s = str(sev)
    if 'HIGH' in s.upper():
      return ('高', 'high')
    if 'MEDIUM' in s.upper():
      return ('中', 'medium')
    if 'INFO' in s.upper():
      return ('信息', 'info')
    return ('低', 'low')

  def report(self, findings: List[Finding], metadata: Dict[str, Any] = None):
    rows = []
    summary = {'high': 0, 'medium': 0, 'low': 0, 'info': 0, 'total': 0}

    for f in findings:
      sev_cn, sev_class = self._map_severity(getattr(f, 'severity', 'LOW'))
      rows.append({
        'severity': str(getattr(f, 'severity', 'LOW')),
        'severity_cn': sev_cn,
        'severity_class': sev_class,
        'scanner': f.scanner,
        'message': f.message,
        'file': f.file,
        'line': f.line,
        'rule_id': f.rule_id,
        'recommendation': f.recommendation,
      })
      summary[sev_class] += 1
      summary['total'] += 1

    tpl = Template(HTML_TMPL)
    with open(self.out, 'w', encoding='utf8') as fh:
      fh.write(
        tpl.render(
          findings=rows,
          summary=summary,
          scan_time=(metadata.get('scan_time') if metadata else ''),
          scanned_path=(metadata.get('scanned_path') if metadata else ''),
        )
      )
